email: marekjm@ozro.pw
description: Viua VM Docs - Viua virtual machine documentation directory
title: Viua VM Docs
url: "http://docs.viuavm.org"

repository_url: "https://github.com/marekjm/viuavm"
releases_url: "https://github.com/marekjm/viuavm/releases"
bugs_url: "https://github.com/marekjm/viuavm/issues"

collections:
    manuals:
        output: true
    tutorials:
        output: true
        title: Tutorials
